cliente/urls.py
from django.urls import path
from cliente import views

app_name = 'cliente'

urlpatterns = [

    # listagem
    # path('', views.welcome, name='welcome'),
    path('lista/cliente/', views.cliente, name='cliente'),
    path('lista/veiculo/', views.veiculo, name='veiculo'),

    # crud cliente
    path('cliente/<int:cliente_id>/detail/', views.cardCliente, name='cardCliente'),
    path('cliente/create/', views.registerCliente, name='create'),
    path('cliente/<int:cliente_id>/update/', views.updateCliente, name='update'),
    path('cliente/<int:cliente_id>/delete/', views.delete, name='delete'),

    # crud veiculo
    path('veiculo/create/', views.registerVeiculo, name='createVeiculo'),
    path('veiculo/<int:veiculo_id>/update/', views.updateVeiculo, name='updateVeiculo'),
]

equipe/urls.py
from django.urls import path
from equipe import views

app_name = 'funcionarios'

urlpatterns = [
    
    #listagens
    path('lista/equipes/', views.equipe, name='equipe'),
    path('lista/funcionarios/', views.funcionario, name='funcionario'),

    # crud
    path('equipe/<int:equipe_id>/detail/', views.equipeDetail, name='detailEquipe'),
    path('create/equipe/', views.registerEquipe, name='createEquipe'),
    path('equipe/<int:equipe_id>/update/', views.updateEquipe, name='updateEquipe'),
    path('equipe/<int:equipe_id>/delete/', views.deleteEquipe, name='deleteEquipe'),

    #crud
    path('funcionario/<int:funcionario_id>/detail/', views.detailFunc, name='detailFunc'),
    path('create/funcionario/', views.registerFuncionario, name='createFunc'),
    path('funcionario/<int:funcionario_id>/update/', views.updateFuncionario, name='updateFunc'),
    path('funcionario/<int:funcionario_id>/delete/', views.deleteFunc, name='deleteFunc'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cliente/', include('cliente.urls')),
    path('servicos/', include('servicos.urls')),
    path('funcionarios/', include('equipe.urls')),
    path('ordem_servico/', include('ordemServico.urls')),
    path('admin/', admin.site.urls),
]

cliente/models.py
from django.db import models

class Cliente(models.Model):
    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=50, blank=True)
    telefone = models.CharField(max_length=50)
    endereco = models.CharField(max_length=254, blank=True)

    def __str__(self) -> str:
        return f'{self.nome} {self.sobrenome}'

class Veiculo(models.Model):
    class Meta:
        verbose_name = 'Veiculo'
        verbose_name_plural = 'Veiculos'

    placa = models.CharField(max_length=7)
    modelo = models.CharField(max_length=50)
    chassi = models.CharField(max_length=50)
    descricao = models.CharField(max_length=254, blank=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True)

    def __str__(self) -> str:
        return self.placa

cliente/forms.py
from django import forms
from django.core.exceptions import ValidationError

from . import models

class ClienteForm(forms.ModelForm):
    class Meta:
        model = models.Cliente
        fields = (
            'nome', 'sobrenome', 'telefone', 'endereco'
        )

    def clean(self):
        cleaned_data = self.cleaned_data
        nome = cleaned_data.get('nome')
        sobrenome = cleaned_data.get('sobrenome')

        if nome == sobrenome:
            msg = ValidationError(
                'Primeiro nome não pode ser igual ao segundo',
                code='invalid'
            )

            self.add_error('nome', msg)
            self.add_error('sobrenome', msg)

        return super().clean()
    
    def clean_names(self):
        nome = self.cleaned_data.get('nome')
        sobrenome = self.cleaned_data.get('sobrenome')

        if nome or sobrenome == 'ABC':
            self.add_error(
                'nome',
                'sobrenome',
                ValidationError(
                    'Não é permitido esses caracteres...',
                    code='invalid'
                )
            )

        return nome, sobrenome

class VeiculoForm(forms.ModelForm):
    class Meta:
        model = models.Veiculo
        fields = (
            'placa', 'modelo', 'chassi', 'descricao', 'cliente'
        )

        def clean(self):
            cleaned_data = self.cleaned_data
            placa = cleaned_data.get('placa')

            if placa and any(letra.islower() for letra in placa):
                msg = ValidationError(
                    'A placa não pode receber letras minusculas',
                    code='invalid'
                )

                self.add_error('placa', msg)

            return placa

cliente/views/cliente_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from cliente.forms import ClienteForm
from cliente.models import Cliente

def registerCliente(request):
    form_action = reverse('cliente:create')
    if request.method == 'POST':
        form = ClienteForm(request.POST)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            cliente = form.save()
            return redirect('cliente:cliente')
        
        return render(
            request,
            'cliente/cliente_create.html',
            context
        )
    
    context = {
        'form': ClienteForm(),
        'form_action': form_action
    }

    return render(
        request,
        'cliente/cliente_create.html',
        context
    )

def updateCliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    form_action = reverse('cliente:update', args=(cliente_id,))
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            form.save()
            return redirect('cliente:update', cliente_id=cliente.pk)
        
        return render(
            request,
            'cliente/cliente_create.html',
            context
        )
    
    context = {
        'form': ClienteForm(instance=cliente),
        'form_action': form_action
    }

    return render(
        request,
        'cliente/cliente_create.html',
        context
    )

def delete(request, cliente_id):
    cliente = get_object_or_404(
        Cliente, pk=cliente_id
    )

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        cliente.delete()
        # veiculos = Veiculo.objects.filter(cliente=cliente)
        # veiculos.delete()
        return redirect('cliente:cliente')
    
    return render(
        request,
        'cliente/cliente_detail.html',
        {
            'cliente': cliente,
            'confirmation': confirmation
        }
    )

cliente/views/cliente_views.py
from django.shortcuts import render, get_object_or_404
from cliente.models import Cliente, Veiculo

# def welcome(request):
#     return render(
#         request,
#         'cliente/welcome.html',
#     )

def cliente(request):
    clientes = Cliente.objects \
        .all().order_by('-id')
    
    context = {
        'clientes': clientes,
        'site_title': 'Clientes - ',
    }

    return render(
        request, 
        "cliente/cliente.html", 
        context
    )

def veiculo(request):
    veiculos = Veiculo.objects \
        .all().order_by('-id')
    
    context = {
        'veiculos': veiculos,
        'site_title': 'Veiculos - ',
    }

    return render(
        request, 
        "veiculo/veiculo.html", 
        context
    )

def cardCliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    veiculos = Veiculo.objects.filter(cliente=cliente)

    site_title = f'{cliente.nome} {cliente.sobrenome} - '

    context = {
        'cliente': cliente,
        'veiculos': veiculos,
        'site_title': site_title
    }

    return render(
        request,
        'cliente/cliente_detail.html',
        context
    )

cliente/views/veiculo_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from cliente.forms import VeiculoForm
from cliente.models import Veiculo

def registerVeiculo(request):
    form_action = reverse('cliente:createVeiculo')
    if request.method == 'POST':
        form = VeiculoForm(request.POST)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            veiculo = form.save()
            return redirect('cliente:veiculo')
        
        return render(
            request,
            'veiculo/veiculo_create.html',
            context
        )
    
    context = {
        'form': VeiculoForm(),
        'form_action': form_action
    }

    return render(
        request,
        'veiculo/veiculo_create.html',
        context
    )

def updateVeiculo(request, veiculo_id):
    veiculo = get_object_or_404(Veiculo, pk=veiculo_id)
    form_action = reverse('cliente:updateVeiculo', args=(veiculo_id,))
    if request.method == 'POST':
        form = VeiculoForm(request.POST, instance=veiculo)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            form.save()
            return redirect('cliente:veiculo')
        
        return render(
            request,
            'veiculo/veiculo_create.html',
            context
        )
    
    context = {
        'form': VeiculoForm(instance=veiculo),
        'form_action': form_action
    }

    return render(
        request,
        'veiculo/veiculo_create.html',
        context
    )

cliente/templates/cliente/cliente.html
{% extends "global/base.html" %}

{% block content %}
    <div class="response-table">
        <div class="table-title">
            <h1 class="title">Clientes</h1>

            <button type="button" class="btn-ordem">
                <a class="add-link" href="{% url "cliente:create" %}">
                    Adicionar Cliente
                </a>
            </button>
        </div>

        <table class="oficina-table">

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">Nome</th>
                    <th class="table-header">Sobrenome</th>
                    <th class="table-header">Telefone</th>
                    <th class="table-header">Endereço</th>
                </tr>
            </thead>

            <tbody>
                {% for cliente in clientes %}

                <tr class="table-row">
                    <td class="table-cel">
                        <a href="{% url "cliente:cardCliente" cliente.id %}" class="table-link">{{ cliente.id }}</a>
                    </td>
                    <td class="table-cel"> {{ cliente.nome }} </td>
                    <td class="table-cel"> {{ cliente.sobrenome }} </td>
                    <td class="table-cel"> {{ cliente.telefone }} </td>
                    <td class="table-cel"> {{ cliente.endereco }} </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock content %}

cliente/templates/cliente/cliente_create.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <div class="header">
      <h2>Cadastro Cliente</h2>
      <button class="close-btn" type="button">
        <a class="btn-add" href="{% url "cliente:cliente" %}">
          <i class="bi bi-arrow-left"></i> Voltar
        </a>
      </button>
    </div>
    
    <form 
      action="{{ form_action }}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}      
      
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
          </div>

          {% if field.name == 'picture' and field.value.url %}
            <div class="form-group">
              <img src="{{ field.value.url }}" alt="">
            </div>
          {% endif %}
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-btn">
        <div class="form-group-btn">
          <button class="btn-send" type="submit">Adicionar Cliente</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

cliente/templates/cliente/cliente_detail.html
{% extends "global/base.html" %}

{% block content %}

    <div class="cliente">
        <h1 class="cliente-name">
            {{ cliente.nome }} {{ cliente.sobrenome }}
        </h1>

        <p><b>ID:</b> {{ cliente.id }}</p>
        <p><b>Telefone:</b> {{ cliente.telefone }}</p>
        <p><b>Endereço:</b> {{ cliente.endereco }}</p>
        {% for veiculo in veiculos %}
            <p><b>Placa:</b> {{ veiculo.placa }}</p>
            <p><b>Modelo:</b> {{ veiculo.modelo }}</p>
            <p><b>Chassi:</b> {{ veiculo.chassi }}</p>
            <p><b>Descrição:</b> {{ veiculo.descricao }}</p>
        {% endfor %}

        <div class="cliente-links">
            <a href="{% url "cliente:update" cliente.id %}" type="button" class="btn-update">
                Atualizar Cliente
            </a>
            <a href="{% url "cliente:createVeiculo" %}" type="button" class="btn-update">
                Cadastrar Veículo
            </a>
            <a href="{% url "cliente:cliente" %}" type="button" class="btn-update">
                Voltar
            </a>

            <form action="{% url "cliente:delete" cliente.id %}" method="POST">
                {% csrf_token %}

                {% if confirmation == 'no' %}
                <input type="hidden" name="confirmation" value="yes" />
                <button class="btn-delete" type="submit">Confirma?</button>
                {% else %}
                <button class="btn-delete" type="submit">Delete</button>
                {% endif %}
            
            </form>
        </div>

    </div>

{% endblock content %}

cliente/templates/cliente/home.html
{% extends "global/base.html" %}

{% block content %}
    <div class="response-table">
        <div class="table-title">
            <h1 class="title">Ordens de Serviços</h1>

            <button type="button" class="btn-ordem">Adicionar Ordem</button>
        </div>

        <table class="oficina-table">

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">Placa</th>
                    <th class="table-header">Descrição</th>
                    <th class="table-header">Equipe</th>
                    <th class="table-header">Serviço</th>
                </tr>
            </thead>

            <tbody>

                <tr class="table-row">
                    <td class="table-cel">
                        <a href="#" class="table-link">1</a>
                    </td>
                    <td class="table-cel">WEK313D</td>
                    <td class="table-cel">Trocar o óleo do veículo</td>
                    <td class="table-cel">Maneiros</td>
                    <td class="table-cel">Troca de Óleo</td>
                </tr>

            </tbody>

        </table>
    </div>
{% endblock content %}

cliente/templates/cliente/welcome.html
{% comment %} {% load static %}

{% block 'welcome' %}

<header>
    <div class="container header-container">
        <div class="header-left">
            <h1>Bem-Vindo ao ScheffelCar</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis est illo <br> nisi  magni ea distinctio ab quibusdam rem qui ex? Quisquam ipsum quaear <br> sint eos alias rem sequi repellendus culpa?
            </p>
            <a href="" class="btn">Entre</a>
        </div>
        <div class="header-right">
            <div class="sq-box">
                <img src="https://github.com/aebyzayn/animated-cars-web-demo/blob/main/Animated%20%20Cars%20Website/car.png?raw=true" alt="">
            </div>
        </div>
    </div>
    <div class="sq-box2"></div>
</header>

<style>
*{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    text-decoration: none;
    list-style: none;
    font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
}
:root{
    --color-primary: #1743e3;
    --color-white: #eaeaea; 
    --color-dark: #333; 
    --color-black: #222; 
}
.btn{
    display: inline-block;
    width: fit-content;
    padding: 12px 28px;
    background: var(--color-primary);
    border: 2px solid var(--color-primary);
    border-radius: 4px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    color: var(--color-white);
    letter-spacing: .4px;
    font-weight: 600;
    transition: .4s ease;
    opacity: 0;
    animation: logoAni 1s ease forwards; 
    animation-delay: 1.3s;
}
.btn:hover{
    background: transparent;
    color: var(--color-primary);
}
.container{
    max-width: 1620px;
    width: 100%;
    margin: 0 auto;
}

/* .......................Start Nav Bar...................... */
/* .......................End Nav Bar...................... */


/* .......................Start Header Section...................... */
header{
    width: 100;
    height: 100vh;
    display: flex;
    align-items: center;
    position: relative;
    overflow: hidden;
}

.header-left{
    max-width: 620px;
    position: relative;
}
.header-left h1{
    font-size: 54px;
    line-height: 1.2;
    color: var(--color-black);
    animation: H1Ani forwards 1s ease;  
    opacity: 0;    
    animation-delay: 1s;  
}
.header-left h3{
    font-size: 40px;
    font-weight: 400;
    color: var(--color-primary);
    margin-top: .5rem;
    animation: H1Ani forwards 1s ease;  
    opacity: 0;    
    animation-delay: .8s;  
}
.header-left p{
    margin: 15px 0 30px;
    line-height: 150%;
    font-size: 16px;
    animation: logoAni forwards 1s ease;  
    opacity: 0;    
    animation-delay: .6s; 
}
.header-container{
    display: grid;
    grid-template-columns: auto auto;
    align-items: center; 
    height: 100%; 
    justify-content: space-between;
}
.header-right{
    position: relative;
    width: 450px;
    height: 450px;
    transform: rotate(45deg);
    right: -7%;   
}
.sq-box{
    height: 100%;
    width: 100%;
    border: 25px solid var(--color-primary);
    background: var(--color-white);
    box-shadow: -15px 15px 15px rgba(0, 0, 0, 0.2) ;
    opacity: 0;
    animation: zoomOut 1s ease forwards; 
    animation-delay: 1.3s;
}
.sq-box img{
    position: absolute;
    transform: rotate(-45deg);
    max-width: 700px;
    top: 130px;
    left: -180px;
    opacity: 0;
    animation: carAni forwards 1s ease;
    animation-delay: 1.6s;
}
.sq-box2{
    position: absolute;
    width: 700px;
    height: 700px;
    background: var(--color-primary);
    transform: rotate(45deg);
    top: -26%;
    right: -26%;
    z-index: -1;
    opacity: 0;
    animation: sqbox2Ani forwards 1s ease;
    animation-delay: .3s;
}
/* .......................End Header Section...................... */



/* .......................Animation Start...................... */
@keyframes logoAni {
    0%{
        transform: translateX(-100px);
        opacity: 0;
    }    
    100%{
        transform: translateX(0);
        opacity: 1;
    }    
}
@keyframes NavliaAni {
    0%{
        transform: translateY(100px);
        opacity: 0;
    }    
    100%{
        transform: translateY(0);
        opacity: 1;
    }    
}
@keyframes socialAni {
    0%{
        transform: translateX(100px) rotate(45deg);
        opacity: 0;
    }    
    100%{
        transform: translateX(0) rotate(45deg);
        opacity: 1;
    }    
}
@keyframes H1Ani {
    0%{
        transform: translateY(-100px) ;
        opacity: 0;
    }    
    100%{
        transform: translateY(0) ;
        opacity: 1;
    }    
}
@keyframes zoomOut {
    0%{
        transform:scale(1.1) ;
        opacity: 0;
    }    
    100%{
        transform: scale(1) ;
        opacity: 1;
    }    
}
@keyframes carAni {
    0%{
        transform: translate(180px, -300px) scale(0) rotate(-45deg);
        opacity: 0;
    }    
    100%{
        transform: translate(0, 0) scale(1) rotate(-45deg);
        opacity: 1;
    }    
}
@keyframes sqbox2Ani {
    0%{
        right: -40%;
        opacity: 0;
    }    
    100%{
        right: -26%;
        opacity: 1;
    }    
}

</style> 


{% endblock  %}  {% endcomment %}