cliente/urls.py
from django.urls import path
from cliente import views

app_name = 'cliente'

urlpatterns = [

    # listagem
    # path('', views.welcome, name='welcome'),
    path('lista/cliente/', views.cliente, name='cliente'),
    path('lista/veiculo/', views.veiculo, name='veiculo'),

    # crud cliente
    path('cliente/<int:cliente_id>/detail/', views.cardCliente, name='cardCliente'),
    path('cliente/create/', views.registerCliente, name='create'),
    path('cliente/<int:cliente_id>/update/', views.updateCliente, name='update'),
    path('cliente/<int:cliente_id>/delete/', views.delete, name='delete'),

    # crud veiculo
    path('veiculo/create/', views.registerVeiculo, name='createVeiculo'),
    path('veiculo/<int:veiculo_id>/update/', views.updateVeiculo, name='updateVeiculo'),
]

equipe/urls.py
from django.urls import path
from equipe import views

app_name = 'funcionarios'

urlpatterns = [
    
    #listagens
    path('lista/equipes/', views.equipe, name='equipe'),
    path('lista/funcionarios/', views.funcionario, name='funcionario'),

    # crud
    path('equipe/<int:equipe_id>/detail/', views.equipeDetail, name='detailEquipe'),
    path('create/equipe/', views.registerEquipe, name='createEquipe'),
    path('equipe/<int:equipe_id>/update/', views.updateEquipe, name='updateEquipe'),
    path('equipe/<int:equipe_id>/delete/', views.deleteEquipe, name='deleteEquipe'),

    #crud
    path('funcionario/<int:funcionario_id>/detail/', views.detailFunc, name='detailFunc'),
    path('create/funcionario/', views.registerFuncionario, name='createFunc'),
    path('funcionario/<int:funcionario_id>/update/', views.updateFuncionario, name='updateFunc'),
    path('funcionario/<int:funcionario_id>/delete/', views.deleteFunc, name='deleteFunc'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cliente/', include('cliente.urls')),
    path('servicos/', include('servicos.urls')),
    path('funcionarios/', include('equipe.urls')),
    path('ordem_servico/', include('ordemServico.urls')),
    path('admin/', admin.site.urls),
]

equipe/models.py
from django.db import models


class Equipe(models.Model):
    nome_equipe = models.CharField(max_length=100)
    especialidade = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.nome_equipe
    
class Funcionario(models.Model):
    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=50)
    cpf = models.CharField(max_length=12)
    # telefone = models.CharField(max_length=50)
    equipe = models.ForeignKey(Equipe, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return f'{self.nome} {self.sobrenome}'

equipe/forms.py
from django import forms
from django.core.exceptions import ValidationError

from . import models

class EquipeForm(forms.ModelForm):
    class Meta:
        model = models.Equipe
        fields = (
            'nome_equipe', 'especialidade'
        )

class FuncForm(forms.ModelForm):
    class Meta:
        model = models.Funcionario
        fields = (
            'nome', 'sobrenome', 'email', 'cpf', 'equipe'
        )

equipe/views/equipe_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from equipe.forms import EquipeForm
from equipe.models import Equipe

def registerEquipe(request):
    form_action = reverse('funcionarios:createEquipe')
    if request.method == 'POST':
        form = EquipeForm(request.POST)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            equipe = form.save()
            return redirect('funcionarios:equipe')
        
        return render(
            request,
            'equipe/equipe_create.html',
            context
        )
    
    context = {
        'form': EquipeForm(),
        'form_action': form_action
    }

    return render(
        request,
        'equipe/equipe_create.html',
        context
    )

def updateEquipe(request, equipe_id):
    equipe = get_object_or_404(Equipe, pk=equipe_id)
    form_action = reverse('funcionarios:updateEquipe', args=(equipe_id,))
    if request.method == 'POST':
        form = EquipeForm(request.POST, instance=equipe)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            form.save()
            return redirect('funcionarios:equipe')
        
        return render(
            request,
            'equipe/equipe_create.html',
            context
        )
    
    context = {
        'form': EquipeForm(instance=equipe),
        'form_action': form_action
    }

    return render(
        request,
        'equipe/equipe_create.html',
        context
    )

def deleteEquipe(request, equipe_id):
    equipe = get_object_or_404(
        Equipe, pk=equipe_id
    )

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        equipe.delete()
        return redirect('funcionarios:equipe')
    
    return render(
        request,
        'funcionarios/equipe_detail.html',
        {
            'equipe': equipe,
            'confirmation': confirmation
        }
    )

equipe/views/equipe_views.py
from django.shortcuts import render, get_object_or_404
from equipe.models import Equipe, Funcionario

def equipe(request):
    equipes = Equipe.objects \
        .all().order_by('-id')
    
    context = {
        'equipes': equipes,
        'site_title': 'Equipes - ',
    }

    return render(
        request,
        'equipe/equipe.html',
        context
    )

def equipeDetail(request, equipe_id):
    equipe = get_object_or_404(Equipe, pk=equipe_id)
    funcionarios = Funcionario.objects.filter(equipe=equipe)

    site_title = f'{equipe.nome_equipe}'

    context = {
        'equipe': equipe,
        'funcionarios': funcionarios,
        'site_title': site_title
    }

    return render(
        request,
        'equipe/equipe_detail.html',
        context
    )

equipe/views/func_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from equipe.forms import FuncForm
from equipe.models import Funcionario

def registerFuncionario(request):
    form_action = reverse('funcionarios:createFunc')
    if request.method == 'POST':
        form = FuncForm(request.POST)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            funcionario = form.save()
            return redirect('funcionarios:funcionario')
        
        return render(
            request,
            'funcionarios/func_create.html',
            context
        )
    
    context = {
        'form': FuncForm(),
        'form_action': form_action
    }

    return render(
        request,
        'funcionarios/func_create.html',
        context
    )

def updateFuncionario(request, funcionario_id):
    equipe = get_object_or_404(Funcionario, pk=funcionario_id)
    form_action = reverse('funcionarios:updateFunc', args=(funcionario_id,))
    if request.method == 'POST':
        form = FuncForm(request.POST, instance=equipe)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            form.save()
            return redirect('funcionarios:funcionario')
        
        return render(
            request,
            'funcionarios/func_create.html',
            context
        )
    
    context = {
        'form': FuncForm(instance=equipe),
        'form_action': form_action
    }

    return render(
        request,
        'funcionarios/func_create.html',
        context
    )

def deleteFunc(request, funcionario_id):
    funcionario = get_object_or_404(
        Funcionario, pk=funcionario_id
    )

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        funcionario.delete()
        return redirect('funcionarios:funcionario')
    
    return render(
        request,
        'funcionarios/func_detail.html',
        {
            'funcionario': funcionario,
            'confirmation': confirmation
        }
    )

equipe/views/func_views.py
from django.shortcuts import render, get_object_or_404
from equipe.models import Funcionario, Equipe

def funcionario(request):
    funcionarios = Funcionario.objects \
        .all().order_by('-id')
    
    context = {
        'funcionarios': funcionarios,
        'site_title': 'Funcionários - ',
    }

    return render(
        request,
        'funcionarios/funcionario.html',
        context
    )

def detailFunc(request, funcionario_id):
    funcionario = get_object_or_404(Funcionario, pk=funcionario_id)
    equipes = Equipe.objects.filter(funcionario=funcionario)

    site_title = f'{funcionario.nome} {funcionario.sobrenome}'

    context = {
        'funcionario': funcionario,
        'equipes': equipes,
        'site_title': site_title
    }

    return render(
        request,
        'funcionarios/func_detail.html',
        context
    )

equipe/templates/funcionarios/func_create.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <div class="header">
      <h2>Cadastro Funcionário</h2>
      <button class="close-btn" type="button">
        <a class="btn-add" href="{% url "funcionarios:funcionario" %}">
          <i class="bi bi-arrow-left"></i> Voltar
        </a>
      </button>
    </div>
    
    <form 
      action="{{ form_action }}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}      
      
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
          </div>

          {% if field.name == 'picture' and field.value.url %}
            <div class="form-group">
              <img src="{{ field.value.url }}" alt="">
            </div>
          {% endif %}
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-btn">
        <div class="form-group-btn">
          <button class="btn-send" type="submit">Adicionar Funcionário</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

equipe/templates/funcionarios/func_detail.html
{% extends "global/base.html" %}

{% block content %}

    <div class="cliente">
        <h1 class="cliente-name">
            {{ funcionario.nome }} {{ funcionario.sobrenome }}
        </h1>

        <p><b>ID:</b> {{ funcionario.id }}</p>
        <p><b>Telefone:</b> {{ funcionario.email }}</p>
        <p><b>Endereço:</b> {{ funcionario.cpf }}</p>
        {% for equipe in equipes %}
            <p><b>Equipe:</b> {{ equipe.nome_equipe }}</p>
            <p><b>Especialidade:</b> {{ equipe.especialidade }}</p>
        {% endfor %}

        <div class="cliente-links">
            <a href="{% url "funcionarios:updateFunc" funcionario.id %}" type="button" class="btn-update">
                Atualizar Funcionario
            </a>
            {% comment %} <a href="{% url "cliente:createVeiculo" %}" type="button" class="btn-update">
                Cadastrar Veículo
            </a> {% endcomment %}
            <a href="{% url "funcionarios:funcionario" %}" type="button" class="btn-update">
                Voltar
            </a>

            <form action="{% url "funcionarios:deleteFunc" funcionario.id %}" method="POST">
                {% csrf_token %}

                {% if confirmation == 'no' %}
                <input type="hidden" name="confirmation" value="yes" />
                <button class="btn-delete" type="submit">Confirma?</button>
                {% else %}
                <button class="btn-delete" type="submit">Delete</button>
                {% endif %}
            
            </form>
        </div>

    </div>

{% endblock content %}

equipe/templates/funcionarios/funcionario.html
{% extends "global/base.html" %}

{% block content %}
    <div class="response-table">
        <div class="table-title">
            <h1 class="title">Funcionários</h1>

            <button type="button" class="btn-ordem">
                <a class="add-link" href="{% url "funcionarios:createFunc" %}">
                    Adicionar Funcionário
                </a>
            </button>
        </div>

        <table class="oficina-table">

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">Nome</th>
                    <th class="table-header">Sobrenome</th>
                    <th class="table-header">Email</th>
                    <th class="table-header">Cpf</th>
                    <th class="table-header">Equipe</th>
                </tr>
            </thead>

            <tbody>
                {% for funcionario in funcionarios %}

                <tr class="table-row">
                    <td class="table-cel">
                        <a href="{% url "funcionarios:detailFunc" funcionario.id %}" class="table-link">{{ funcionario.id }}</a>
                    </td>
                    <td class="table-cel"> {{ funcionario.nome }} </td>
                    <td class="table-cel"> {{ funcionario.sobrenome }} </td>
                    <td class="table-cel"> {{ funcionario.email }} </td>
                    <td class="table-cel"> {{ funcionario.cpf }} </td>
                    <td class="table-cel"> {{ funcionario.equipe }} </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock content %}