equipe/urls.py
from django.urls import path
from equipe import views

app_name = 'funcionarios'

urlpatterns = [
    
    #listagens
    path('lista/equipes/', views.equipe, name='equipe'),
    path('lista/funcionarios/', views.funcionario, name='funcionario'),

    # crud
    path('equipe/<int:equipe_id>/detail/', views.equipeDetail, name='detailEquipe'),
    path('create/equipe/', views.registerEquipe, name='createEquipe'),
    path('equipe/<int:equipe_id>/update/', views.updateEquipe, name='updateEquipe'),
    path('equipe/<int:equipe_id>/delete/', views.deleteEquipe, name='deleteEquipe'),

    #crud
    path('funcionario/<int:funcionario_id>/detail/', views.detailFunc, name='detailFunc'),
    path('create/funcionario/', views.registerFuncionario, name='createFunc'),
    path('funcionario/<int:funcionario_id>/update/', views.updateFuncionario, name='updateFunc'),
    path('funcionario/<int:funcionario_id>/delete/', views.deleteFunc, name='deleteFunc'),
]

ordemServico/urls.py
from django.urls import path
from ordemServico import views

app_name = 'ordem'

urlpatterns = [
    path('home/', views.home, name='home'),

    path('<int:ordemServico_id>/details/', views.detailOrdem, name='detailOrdem'),
    path('create/', views.registerOrdem, name='createOrdem'),
    path('<int:ordemServico_id>/update/', views.updateOrdem, name='updateOrdem'),
    path('<int:ordemServico_id>/delete/', views.deleteOrdem, name='deleteOrdem')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cliente/', include('cliente.urls')),
    path('servicos/', include('servicos.urls')),
    path('funcionarios/', include('equipe.urls')),
    path('ordem_servico/', include('ordemServico.urls')),
    path('admin/', admin.site.urls),
]

ordemServico/models.py
from django.db import models
from cliente.models import Cliente, Veiculo
from equipe.models import Equipe
from servicos.models import Servico, Peca

class OrdemServico(models.Model):
    veiculo = models.ForeignKey(Veiculo, on_delete=models.SET_NULL, null=True)
    descricao = models.TextField(max_length=254)
    data_inicio = models.DateField()
    data_entrega = models.DateField(null=True)
    equipe = models.ForeignKey(Equipe, on_delete=models.SET_NULL, null=True)
    servico = models.ManyToManyField(Servico, null=True)
    pecas = models.ManyToManyField(Peca, null=True)
    valor_final = models.DecimalField(decimal_places=2, max_digits=8, null=True)

ordemServico/forms.py
from django import forms

from . import models
from servicos.models import Servico, Peca

class OrdemServicoForm(forms.ModelForm):
    valor_final = forms.DecimalField(label='Valor Total', required=False)
    class Meta:
        model = models.OrdemServico
        fields = (
            'veiculo', 'descricao', 'data_inicio', 'equipe', 'servico', 'pecas',
        )

ordemServico/views/ordemServico.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from ordemServico.forms import OrdemServicoForm
from ordemServico.models import OrdemServico
from decimal import Decimal
from cliente.models import Veiculo

def home(request):
    ordens = OrdemServico.objects \
        .all().order_by('-id')
    
    context = {
        'ordens': ordens,
        'site_title': 'Ordem Serviço - ',
    }
    return render(request, "ordem/home.html", context)

def registerOrdem(request):
    form_action = reverse('ordem:createOrdem')
    if request.method == 'POST':
        form = OrdemServicoForm(request.POST)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            ordem = form.save()
            return redirect('ordem:home')
        
        return render(
            request,
            'ordem/ordem_create.html',
            context
        )
    
    context = {
        'form': OrdemServicoForm(),
        'form_action': form_action
    }

    return render(
        request,
        'ordem/ordem_create.html',
        context
    )

def updateOrdem(request, ordemServico_id):
    ordem = get_object_or_404(OrdemServico, pk=ordemServico_id)
    form_action = reverse('ordem:updateOrdem', args=(ordemServico_id,))
    if request.method == 'POST':
        form = OrdemServicoForm(request.POST, instance=ordem)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            form.save()
            return redirect('ordem:detailsOrdem')
        
        return render(
            request,
            'ordem/ordem_create.html',
            context
        )
    
    context = {
        'form': OrdemServicoForm(instance=ordem),
        'form_action': form_action
    }

    return render(
        request,
        'ordem/ordem_create.html',
        context
    )

def deleteOrdem(request, ordemServico_id):
    ordem = get_object_or_404(OrdemServico, pk=ordemServico_id)

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        ordem.delete()
        return redirect('ordem:home')
    
    return render(
        request,
        'ordem/ordem_detail.html',
        {
            'ordem': ordem,
            'confirmation': confirmation
        }
    )

def concluirOrdem(request, ordemServico_id):
    ...

def detailOrdem(request, ordemServico_id):
    ordem = get_object_or_404(OrdemServico, pk=ordemServico_id)
    # veiculo = Veiculo.objects.get(placa=ordem.placa)
    veiculo = ordem.veiculo

    site_title = f'{veiculo.placa}'

    context = {
        'ordem': ordem,
        'veiculo': veiculo,
        'site_title': site_title
    }

    return render(
        request,
        'ordem/ordem_detail.html',
        context
    )

ordemServico/templates/ordem/home.html
{% extends "global/base.html" %}

{% block content %}
    <div class="response-table">
        <div class="table-title">
            <h1 class="title">Ordens de Serviços</h1>

            <button type="button" class="btn-ordem">
                <a class="add-link" href="{% url "ordem:createOrdem" %}">
                    Adicionar Ordem
                </a>
            </button>
        </div>

        <table class="oficina-table">

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">Placa</th>
                    <th class="table-header">Descrição</th>
                    <th class="table-header">Equipe</th>
                </tr>
            </thead>

            <tbody>
                {% for ordem in ordens %}
                <tr class="table-row">
                    <td class="table-cel">
                        <a href="{% url 'ordem:detailOrdem' ordem.id %}" class="table-link"> {{ ordem.id }}</a>
                    </td>
                    <td class="table-cel">{{ ordem.veiculo }}</td>
                    <td class="table-cel">{{ ordem.descricao }}</td>
                    <td class="table-cel"> {{ ordem.equipe }} </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock content %}

ordemServico/templates/ordem/ordem_create.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <div class="header">
      <h2>Criar Ordem de Serviço</h2>
      <button class="close-btn" type="button">
        <a class="btn-add" href="{% url "ordem:home" %}">
          <i class="bi bi-arrow-left"></i> Voltar
        </a>
      </button>
    </div>
    
    <form 
      action="{{ form_action }}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}      
      
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
          </div>

          {% if field.name == 'picture' and field.value.url %}
            <div class="form-group">
              <img src="{{ field.value.url }}" alt="">
            </div>
          {% endif %}
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-btn">
        <div class="form-group-btn">
          <button class="btn-send" type="submit">Adicionar Ordem</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

ordemServico/templates/ordem/ordem_detail.html
{% extends "global/base.html" %}

{% block content %}

    <div class="cliente">
        <h1 class="cliente-name">
            Placa Veículo: {{ veiculo.placa }}
        </h1>

        <p><b>ID:</b> {{ ordem.id }}</p>
        <p><b>Modelo:</b> {{ ordem.veiculo.modelo }}</p>
        <p><b>Cliente:</b> {{ ordem.veiculo.cliente }}</p>
        <p><b>Descrição:</b> {{ ordem.descricao }}</p>
        <p><b>Equipe:</b> {{ ordem.equipe }}</p>
        <p><b>Peça:</b> {{ ordem.peca }}</p>
        <p><b>Serviço:</b> {{ ordem.servico }}</p>

        <div class="cliente-links">
            <a href="{% url "ordem:updateOrdem" ordem.id %}" type="button" class="btn-update">
                Atualizar Ordem de Serviço
            </a>
            <a href="{% url "ordem:createOrdem" %}" type="button" class="btn-update">
                Concluir Ordem
            </a>
            <a href="{% url "ordem:home" %}" type="button" class="btn-update">
                Voltar
            </a>

            <form action="{% url "ordem:deleteOrdem" ordem.id %}" method="POST">
                {% csrf_token %}

                {% if confirmation == 'no' %}
                <input type="hidden" name="confirmation" value="yes" />
                <button class="btn-delete" type="submit">Confirma?</button>
                {% else %}
                <button class="btn-delete" type="submit">Delete</button>
                {% endif %}
            
            </form>"
        </div>

    </div>

{% endblock content %}