cliente/urls.py
from django.urls import path
from cliente import views

app_name = 'cliente'

urlpatterns = [

    # listagem
    # path('', views.welcome, name='welcome'),
    path('lista/cliente/', views.cliente, name='cliente'),
    path('lista/veiculo/', views.veiculo, name='veiculo'),

    # crud cliente
    path('cliente/<int:cliente_id>/detail/', views.cardCliente, name='cardCliente'),
    path('cliente/create/', views.registerCliente, name='create'),
    path('cliente/<int:cliente_id>/update/', views.updateCliente, name='update'),
    path('cliente/<int:cliente_id>/delete/', views.delete, name='delete'),

    # crud veiculo
    path('veiculo/create/', views.registerVeiculo, name='createVeiculo'),
    path('veiculo/<int:veiculo_id>/update/', views.updateVeiculo, name='updateVeiculo'),
]

equipe/urls.py
from django.urls import path
from equipe import views

app_name = 'funcionarios'

urlpatterns = [
    
    #listagens
    path('lista/equipes/', views.equipe, name='equipe'),
    path('lista/funcionarios/', views.funcionario, name='funcionario'),

    # crud
    path('equipe/<int:equipe_id>/detail/', views.equipeDetail, name='detailEquipe'),
    path('create/equipe/', views.registerEquipe, name='createEquipe'),
    path('equipe/<int:equipe_id>/update/', views.updateEquipe, name='updateEquipe'),
    path('equipe/<int:equipe_id>/delete/', views.deleteEquipe, name='deleteEquipe'),

    #crud
    path('funcionario/<int:funcionario_id>/detail/', views.detailFunc, name='detailFunc'),
    path('create/funcionario/', views.registerFuncionario, name='createFunc'),
    path('funcionario/<int:funcionario_id>/update/', views.updateFuncionario, name='updateFunc'),
    path('funcionario/<int:funcionario_id>/delete/', views.deleteFunc, name='deleteFunc'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cliente/', include('cliente.urls')),
    path('servicos/', include('servicos.urls')),
    path('funcionarios/', include('equipe.urls')),
    path('ordem_servico/', include('ordemServico.urls')),
    path('admin/', admin.site.urls),
]

servicos/urls.py
from django.urls import path
from servicos import views

app_name = 'servicos'

urlpatterns = [

    # listagens
    path('lista/pecas/', views.peca, name='pecas'),
    path('lista/servicos/', views.servico, name='servicos'),

    # Crud peças
    path('peca/create/', views.registerPeca, name='createPeca'),
    path('peca/<int:peca_id>/update/', views.updatePeca, name='updatePeca'),

    # Crud Serviços
    path('servicos/create/', views.resgisterServico, name='createServico'),
    path('servicos/<int:servico_id>/update', views.updateServico, name='updateServico'),
]

servicos/models.py
from django.db import models

class Peca(models.Model):
    nome_peca = models.CharField(max_length=100)
    estoque = models.PositiveIntegerField()
    valor = models.DecimalField(decimal_places=2, max_digits=8)

    def __str__(self) -> str:
        return self.nome_peca
    
class Servico(models.Model):
    nome_servico = models.CharField(max_length=100)
    descricao = models.TextField(max_length=254)
    valor = models.DecimalField(decimal_places=2, max_digits=8)

    def __str__(self) -> str:
        return self.nome_servico

servicos/forms.py
from django import forms
from django.core.exceptions import ValidationError

from . import models

class PecaForm(forms.ModelForm):
    class Meta:
        model = models.Peca
        fields = (
            'nome_peca', 'estoque', 'valor',
        )

class ServicoForm(forms.ModelForm):
    class Meta:
        model = models.Servico
        fields = (
            'nome_servico', 'descricao', 'valor',
        )

servicos/views/peca_forms.py
from django.shortcuts import render
from servicos.forms import PecaForm

def registerPeca(request):
    form = PecaForm()

    context = {
        'form': form,
    }

    return render(
        request,
        'pecas/peca_create.html',
        context,
    )

servicos/views/peca_views.py
from django.shortcuts import render
from servicos.models import Peca

def peca(request):
    pecas = Peca.objects \
        .all().order_by('-id')
    
    context = {
        'pecas': pecas,
        'site_title': 'Peças - ',
    }

    return render(
        request,
        'pecas/pecas.html',
        context
    )

servicos/views/servico_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from servicos.forms import ServicoForm
from servicos.models import Servico


def resgisterServico(request):
    form_action = reverse('servicos:createServico')
    if request.method == 'POST':
        form = ServicoForm(request.POST)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            servico = form.save()
            return redirect('servicos:servicos')
        
        return render(
            request,
            'servicos/servico_create.html',
            context
        )
    
    context = {
        'form': ServicoForm(),
        'form_action': form_action
    }

    return render(
        request,
        'servicos/servico_create.html',
        context
    )

def updateServico(request, servico_id):
    servico = get_object_or_404(Servico, pk=servico_id)
    form_action = reverse('servicos:updateServico', args=(servico_id,))
    if request.method == 'POST':
        form = ServicoForm(request.POST, instance=servico)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            form.save()
            return redirect('servicos:servicos')
        
        return render(
            request,
            'servicos/servico_create.html',
            context
        )
    
    context = {
        'form': ServicoForm(instance=servico),
        'form_action': form_action
    }

    return render(
        request,
        'servicos/servico_create.html',
        context
    )

servicos/views/servico_views.py
from django.shortcuts import render
from servicos.models import Servico

def servico(request):
    servicos = Servico.objects \
        .all().order_by('-id')
    
    context = {
        'servicos': servicos,
        'site_title': 'Serviços - ',
    }

    return render(
        request,
        'servicos/servico.html',
        context
    )

servicos/templates/pecas/peca_create.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <div class="header">
      <h2>Cadastro Peças</h2>
      <button class="close-btn" type="button">
        <a class="btn-add" href="{% url "cliente:cliente" %}">
          <i class="bi bi-arrow-left"></i> Voltar
        </a>
      </button>
    </div>
    
    <form 
      action="{{ form_action }}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}      
      
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
          </div>

          {% if field.name == 'picture' and field.value.url %}
            <div class="form-group">
              <img src="{{ field.value.url }}" alt="">
            </div>
          {% endif %}
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-btn">
        <div class="form-group-btn">
          <button class="btn-send" type="submit">Adicionar Peça</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

servicos/templates/pecas/pecas.html
{% extends "global/base.html" %}

{% block content %}

<div class="response-table">
    <div class="table-title">
        <h1 class="title">Peças</h1>

        <button type="button" class="btn-ordem">
            <a class="add-link" href="{% url "cliente:create" %}">
                Adicionar Peça
            </a>
        </button>
    </div>

    <table class="oficina-table">

        <thead>
            <tr class="table-row table-row-header">
                <th class="table-header">ID</th>
                <th class="table-header">Nome</th>
                <th class="table-header">Estoque</th>
                <th class="table-header">Valor Unitário</th>
            </tr>
        </thead>

        <tbody>
            {% for cliente in clientes %}

            <tr class="table-row">
                <td class="table-cel">
                    <a href="{% url "cliente:cardCliente" cliente.id %}" class="table-link">{{ cliente.id }}</a>
                </td>
                <td class="table-cel"> {{ cliente.nome }} </td>
                <td class="table-cel"> {{ cliente.sobrenome }} </td>
                <td class="table-cel"> {{ cliente.telefone }} </td>
                <td class="table-cel"> {{ cliente.endereco }} </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>

{% endblock content %}